import "./globals.css";
import type { Metadata } from "next";

import { Navbar, Footer } from "@/components";

export const metadata: Metadata = {
  title: "Emulsion AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
